adcs:
  mode: normal
  timeout: 10
  koe:
    # Units in meters and degrees.
    epch: 2458529.50
    sma: 6791113.16
    ecc: .0014246
    incl: 51.30431
    raan: 245.32261
    argp: 33.54134
    tran: 312.21070
    drag: 2.2
  sc:
    inertia: [0.0108, 0.0108, 0.0108]
    jd0: 2458529.50
  tledata:
    meananom: 0
    lastyear: 2019
    meanmot: 15.5
  wrldmagm: "WMM.COF"